from detectron2.config import CfgNode as CN

def add_config(cfg):
    _C = cfg
    _C.OPENSET = CN()
    _C.OPENSET.ENABLE_REW = False
    
    _C.OPENSET.REW = CN()
    _C.OPENSET.REW.AE_INTER = [64, 32, 16, 8, 4]
    _C.OPENSET.REW.FITER_PERCENT = 0.2
    _C.OPENSET.REW.HARD_THR = False
    _C.OPENSET.REW.ENABLE_SL = True
    _C.OPENSET.REW.GAMMA = 2.0
    _C.OPENSET.REW.ALPHA = 1.0
    _C.OPENSET.REW.SAMPLING_ITERS = 2500
    _C.OPENSET.REW.NUM_SAMPLES = 160000
    _C.OPENSET.REW.UPDATE_WEIBULL = False

    _C.OPENSET.ENABLE_OLN = False
    _C.OPENSET.OLN_INFERENCE = False
    _C.OPENSET.INFERENCE_SELT_TRAIN = False
    _C.OPENSET.OLN = CN()
    _C.OPENSET.OLN.IOU_LABELS = [-1, 1]
    _C.OPENSET.OLN.IOU_THRESHOLDS = [0.3]
    _C.OPENSET.OLN.NMS_THRESH = 0.7
    _C.OPENSET.OLN.POSITIVE_FRACTION = 1.0
    _C.OPENSET.OLN.POST_NMS_TOPK_TEST = 10000
    _C.OPENSET.OLN.POST_NMS_TOPK_TRAIN = 10000
    _C.OPENSET.OLN.PRE_NMS_TOPK_TEST = 2000
    _C.OPENSET.OLN.PRE_NMS_TOPK_TRAIN = 2000
    _C.OPENSET.OLN.BATCH_SIZE_PER_IMAGE = 256
    
    _C.OPENSET.NUM_KNOWN_CLASSES = 20
    _C.OPENSET.NUM_PREV_KNOWN_CLASSES = 0
    _C.OPENSET.EVAL_UNKNOWN = False
    _C.OPENSET.OUTPUT_PATH_REW = "./"
    

    return _C
    
   
