_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "models/current_detectron2_Head.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: OLN_RPN
  ROI_HEADS:
    NAME: StandardROIHeads_OLN
    NUM_CLASSES: 81
    SCORE_THRESH_TEST: 0.05
  RPN:
    HEAD_NAME: OLN_RPNHead
  META_ARCHITECTURE: OLN_BOX
INPUT:
  FORMAT: "RGB"
SOLVER:
  AMP:
    ENABLED: True
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (16000, )
  MAX_ITER: 23000
TEST:
  EVAL_PERIOD: 10000
DATASETS:
  TRAIN: ('sowod_train_t1_st',)
  TEST: ("sowod_val",)
OPENSET:
  ENABLE_OLN: True
  OLN_INFERENCE: False
  NUM_KNOWN_CLASSES: 19
  NUM_PREV_KNOWN_CLASSES: 0
  CALIBRATE: True
  CALIBRATE_WEIGHT: 5.0
  FILTER_THRESH: 0.3