_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: OLN_RPN
  ROI_HEADS:
    NAME: StandardROIHeads_OLN
    NUM_CLASSES: 81
    SCORE_THRESH_TEST: 0.05
  RPN:
    HEAD_NAME: OLN_RPNHead
  META_ARCHITECTURE: OLN_BOX
INPUT:
  FORMAT: "RGB"
SOLVER:
  AMP:
    ENABLED: True
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: []
  MAX_ITER: 40000
DATASETS:
  TRAIN: ('sowod_train_t3_st',)
  TEST: ("sowod_val",)
OPENSET:
  ENABLE_OLN: True
  OLN_INFERENCE: False
  NUM_KNOWN_CLASSES: 60
  NUM_PREV_KNOWN_CLASSES: 40
