_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "models/current_detectron2_Head.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  ROI_HEADS:
    NUM_CLASSES: 81
  PROPOSAL_GENERATOR:
    NAME: OFFLINE_AE_RPN
  RPN:
    HEAD_NAME: OFFLINE_AE_RPNHead
  META_ARCHITECTURE: OFFLINE_AE
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (220, 252, 284, 316, 348 , 380, 412, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216, 1248)
SOLVER:
  AMP:
    ENABLED: True
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (60000, )
  MAX_ITER: 90000
DATASETS:
  TRAIN: ('sowod_train',)
  TEST: []
OPENSET:
  ENABLE_REW: True
  REW:
    UPDATE_WEIBULL: False
  ENABLE_OLN: False
  OLN_INFERENCE: False
  NUM_KNOWN_CLASSES: 80 
  NUM_PREV_KNOWN_CLASSES: 0
