_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "SoCo_FPN_Star_400ep/current_detectron2_Head.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  ROI_HEADS:
    NUM_CLASSES: 81
  PROPOSAL_GENERATOR:
    NAME: OFFLINE_AE_RPN
  RPN:
    HEAD_NAME: OFFLINE_AE_RPNHead
  META_ARCHITECTURE: OFFLINE_AE
INPUT:
  FORMAT: "RGB"
SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 16
  BASE_LR: 0.0000002
  STEPS: []
  MAX_ITER: 3000
DATASETS:
  TRAIN: ("mowod_train_t2",)
  TEST: []
OPENSET:
  ENABLE_REW: True
  ENABLE_OLN: False
  OLN_INFERENCE: False
  NUM_KNOWN_CLASSES: 40
  NUM_PREV_KNOWN_CLASSES: 0
  REW:
    SAMPLING_ITERS: 2500
    UPDATE_WEIBULL: True