_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "models/current_detectron2_Head.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: OLN_RPN
  ROI_HEADS:
    NAME: StandardROIHeads_OLN
    NUM_CLASSES: 81
    SCORE_THRESH_TEST: 0.05
  RPN:
    HEAD_NAME: OLN_RPNHead
  META_ARCHITECTURE: OLN_BOX
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (220, 252, 284, 316, 348 , 380, 412, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088)
SOLVER:
  AMP:
    ENABLED: True
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (30000, 50000)
  MAX_ITER: 60000
TEST:
  EVAL_PERIOD: 10000
DATASETS:
  TRAIN: ('mowod_train_t1_fs',)
  TEST: ("mowod_val",)
OPENSET:
  ENABLE_OLN: True
  OLN_INFERENCE: False
  NUM_KNOWN_CLASSES: 20
  NUM_PREV_KNOWN_CLASSES: 0
